version: '3'
services:
  postgres:
    build: .
    image: my/postgres9.1
    container_name: 'postgres'
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - example.sql:/docker-entrypoint-initdb.d/example.sql

volumes:
  postgres-data:
    driver: local
